function [ M ] = mass_hermite( mat, p )
%MASS_HERMITE Return discrete identity operator

load('local_matrices.mat'); % local matrices are generated by hermite_basis.m

N = length(p);

inds = [1:(N-1); (1:(N-1))+N; 2:N; (2:N)+N];

M = sparse(2*N, 2*N);

% loop over local system matrix
for itr=1:4
    for jtr=1:4
        % a(x) u v
        abu = s3{jtr, itr}(mat(1:(end-1)), mat(2:end), p(1:(end-1)), p(2:end));
        M = M + sparse(inds(itr, :), inds(jtr, :), abu, 2*N, 2*N);
    end
end

end

